### ISSUE TITLE
Better CHANGELOG vs RELEASENOTES handling

### ISSUE THREAD

**Issue by patrikspiess** [migros/fotoobo#134]
The changelog is also used as relase notes document for every relase. This means that for every release the complete changelog (also historical entries) is listes as release notes.
Instead we should use a release notes with only information about the latest relase. The relase prcocess should then copy the information from the rlease notes to the changelog.

**Comment by lucmurer** [comment]
should be fixed with PR #136, lets test this on the next release until closing this issue.
