### ISSUE TITLE
Make .make-release.sh prefill WHATSNEW, not only empty it

### ISSUE THREAD

**Issue by lucmurer** [migros/fotoobo#140]
Insert "### Added", "### Changed" and possibly "### Deleted" to the "WHATSNEW" instead of just emptying it in ".make_release.sh"

**Comment by patrikspiess** [comment]
I fixed that. Now the WHATSNEW file is not deleted anymore in .make_release. Rather that that I changed .tag_release to first push the release with tag and after that recreate WHATSNEW with template and push it again.
