### ISSUE TITLE
Traceback when a FortiGate misses hostname or token in inventory

### ISSUE THREAD

**Issue by patrikspiess** [migros/fotoobo#156]
If you miss to specify a hostname or a token in the inventory file there is a traceback when trying to access such a device:

The follwing errors may occur:

    TypeError: FortiGate.__init__() missing 1 required positional argument: 'hostname'
    TypeError: FortiGate.__init__() missing 1 required positional argument: 'token'
    TypeError: FortiGate.__init__() missing 2 required positional arguments: 'hostname' and 'token'

Check existense and handle it somehow.

**Comment by lucmurer** [comment]
closed with PR #157
