### ISSUE TITLE
Review cli command structure

### ISSUE THREAD

**Issue by patrikspiess** [migros/fotoobo#28]
Command structure seems more accidental than intentional at the moment: Sometimes the command structure is very specific (`fotoobo fgt check hamaster`), sometimes there seems to lack a subcommand (`fotoobo convert checkpoint`).

I think there should be a general structure like:
* `fotoobo <asset-type> <do-word> <object>` (e.g. `fotoobo fgt check hamaster`)
* or `fotoobo <do-word> <asset-type> <object>` (e.g. `fotoobo convert checkpoint assets`)

**Comment by lucmurer** [comment]
Sometimes there are default values for positional arguments (or default behavior when a positional argument is left empty). Check, whether this makes sense (we cannot have more than one optional argument, but several optional options).
