### ISSUE TITLE
install error with poetry 1.4.1

### ISSUE THREAD

**Issue by stoege** [migros/fotoobo#65]
on macos, poetry 1.4.1 was release a few days ago.

**Problem**
i was not able to install fotoobo with 'poetry install'
```
• Installing black (22.10.0): Failed

  _WheelFileValidationError

  ["In /Users/MYUSERNAME/Library/Caches/pypoetry/artifacts/9a/87/53/8a817f0bf6562226d9de0d3ad0eb2eb28c8191e978d21740991796e053/black-22.10.0-1fixedarch-cp311-cp311-macosx_11_0_x86_64.whl, hash / size of black-22.10.0.dist-info/WHEEL didn't match RECORD"]

  at /usr/local/Cellar/poetry/1.4.1/libexec/lib/python3.11/site-packages/installer/sources.py:289 in validate_record
      285│                         f"In {self._zipfile.filename}, hash / size of {item.filename} didn't match RECORD"
      286│                     )
      287│ 
      288│         if issues:
    → 289│             raise _WheelFileValidationError(issues)
      290│ 
      291│     def get_contents(self) -> Iterator[WheelContentElement]:
      292│         """Sequential access to all contents of the wheel (including dist-info files).
      293│ 
```
**Solution**
downgrad poetry locall to the previous version:
```
poetry self update 1.4.0
```

and all seems to work fine ...

**Comment by patrikspiess** [comment]
I was not able to reproduce the same in a Windows/WSL Ubuntu 22.04 installation.
Black 22.10.0 was successfully installed with Poetry 1.4.1:

    pspiess@...:~/projects/test$ poetry -V
    Poetry (version 1.4.1)
    pspiess@...:~/projects/test$ poetry run black --version
    black, 22.10.0 (compiled: yes)
    Python (CPython) 3.10.7

**Comment by patrikspiess** [comment]
It was even not reproducable on a Mac by the reporting party.
We assume it was a temporary issue.
